package com.nuramin.calculator.puzzle;

import com.nuramin.calculator.util.ExprParser;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Game logic for Number Target Puzzle: generate solvable puzzles, validate expression,
 * level/difficulty, attempts, score. Modular: no Android dependencies.
 *
 * <p>Puzzles are generated by brute force: four numbers and a target that matches at least one
 * linear expression {@code n0 op n1 op n2 op n3} evaluated with {@link ExprParser} (standard
 * precedence). This matches what the UI can build without parentheses.
 */
public final class NumberTargetPuzzleEngine {

    public static final int TARGET_SCORE = 100;
    public static final int MAX_ATTEMPTS_PER_PUZZLE = 3;
    public static final int NUMBERS_COUNT = 4;
    public static final int PUZZLES_PER_LEVEL = 3;

    private static final char[] BINARY_OPS = {'+', '-', '*', '/'};
    private static final Pattern INTEGER_TOKEN = Pattern.compile("\\d+");

    private final Random random = new Random();

    private int level = 1;
    private int score = 0;
    private int puzzlesSolvedThisLevel = 0;
    private int attemptsLeft = MAX_ATTEMPTS_PER_PUZZLE;

    private int[] currentNumbers = new int[NUMBERS_COUNT];
    private int currentTarget;

    public int getLevel() {
        return level;
    }

    public int getScore() {
        return score;
    }

    public int getAttemptsLeft() {
        return attemptsLeft;
    }

    public int[] getCurrentNumbers() {
        return currentNumbers.clone();
    }

    public int getCurrentTarget() {
        return currentTarget;
    }

    /** Score reward for current level (10, 12, or 15). */
    public int getScoreReward() {
        if (level <= 1) return 10;
        if (level == 2) return 12;
        return 15;
    }

    /** Reset game state (score 0, level 1). */
    public void reset() {
        level = 1;
        score = 0;
        puzzlesSolvedThisLevel = 0;
        attemptsLeft = MAX_ATTEMPTS_PER_PUZZLE;
        generatePuzzle();
    }

    /**
     * Generate a new puzzle: 4 numbers and a target that can be produced from them with three
     * binary operators (no parentheses), using the same rules as {@link ExprParser}.
     */
    public void generatePuzzle() {
        int numMin, numMax, targetMin, targetMax;
        if (level <= 1) {
            numMin = 1;
            numMax = 10;
            targetMin = 10;
            targetMax = 30;
        } else if (level == 2) {
            numMin = 1;
            numMax = 15;
            targetMin = 30;
            targetMax = 80;
        } else {
            numMin = 2;
            numMax = 20;
            targetMin = 80;
            targetMax = 150;
        }

        for (int outer = 0; outer < 200; outer++) {
            for (int i = 0; i < NUMBERS_COUNT; i++) {
                currentNumbers[i] = numMin + random.nextInt(numMax - numMin + 1);
            }
            List<Integer> targets = listReachableTargetsInRange(currentNumbers, targetMin, targetMax);
            if (!targets.isEmpty()) {
                currentTarget = targets.get(random.nextInt(targets.size()));
                attemptsLeft = MAX_ATTEMPTS_PER_PUZZLE;
                return;
            }
        }
        applyGuaranteedSolvableFallback(targetMin, targetMax);
        attemptsLeft = MAX_ATTEMPTS_PER_PUZZLE;
    }

    /**
     * All targets in [min, max] reachable by some permutation and operator triple (linear form).
     */
    private static List<Integer> listReachableTargetsInRange(int[] nums, int min, int max) {
        List<Integer> out = new ArrayList<>();
        List<int[]> perms = new ArrayList<>(24);
        collectPermutations(nums, perms);
        for (int[] p : perms) {
            for (int i = 0; i < 4; i++) {
                for (int j = 0; j < 4; j++) {
                    for (int k = 0; k < 4; k++) {
                        int v = evalLinearNoParens(p, i, j, k);
                        if (v >= min && v <= max && v > 0) {
                            out.add(v);
                        }
                    }
                }
            }
        }
        return out;
    }

    /** Used by unit tests: puzzle is solvable in linear form without parentheses. */
    static boolean hasLinearSolution(int[] nums, int target) {
        List<int[]> perms = new ArrayList<>(24);
        collectPermutations(nums, perms);
        for (int[] p : perms) {
            for (int i = 0; i < 4; i++) {
                for (int j = 0; j < 4; j++) {
                    for (int k = 0; k < 4; k++) {
                        int v = evalLinearNoParens(p, i, j, k);
                        if (v == target) {
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }

    private static void collectPermutations(int[] nums, List<int[]> out) {
        for (int i0 = 0; i0 < 4; i0++) {
            for (int i1 = 0; i1 < 4; i1++) {
                if (i1 == i0) continue;
                for (int i2 = 0; i2 < 4; i2++) {
                    if (i2 == i0 || i2 == i1) continue;
                    for (int i3 = 0; i3 < 4; i3++) {
                        if (i3 == i0 || i3 == i1 || i3 == i2) continue;
                        out.add(new int[]{nums[i0], nums[i1], nums[i2], nums[i3]});
                    }
                }
            }
        }
    }

    /**
     * Evaluate {@code perm[0] op perm[1] op perm[2] op perm[3]} with ExprParser (×÷ precedence).
     */
    private static int evalLinearNoParens(int[] perm, int op0, int op1, int op2) {
        String expr = perm[0] + "" + BINARY_OPS[op0] + perm[1] + BINARY_OPS[op1] + perm[2] + BINARY_OPS[op2] + perm[3];
        try {
            double r = new ExprParser(expr).parse();
            if (Double.isNaN(r) || Double.isInfinite(r)) {
                return Integer.MIN_VALUE;
            }
            if (r != Math.floor(r)) {
                return Integer.MIN_VALUE;
            }
            if (r <= 0 || r > Integer.MAX_VALUE) {
                return Integer.MIN_VALUE;
            }
            return (int) Math.round(r);
        } catch (Exception e) {
            return Integer.MIN_VALUE;
        }
    }

    private void applyGuaranteedSolvableFallback(int targetMin, int targetMax) {
        if (level <= 1) {
            currentNumbers = new int[]{2, 2, 3, 3};
            currentTarget = clamp(10, targetMin, targetMax);
        } else if (level == 2) {
            currentNumbers = new int[]{5, 5, 10, 10};
            currentTarget = clamp(30, targetMin, targetMax);
        } else {
            currentNumbers = new int[]{15, 15, 20, 30};
            currentTarget = clamp(80, targetMin, targetMax);
        }
    }

    private static int clamp(int value, int min, int max) {
        return Math.max(min, Math.min(max, value));
    }

    /**
     * Validate and evaluate expression. Returns SubmitResult.
     * Expression must use each of the 4 numbers exactly once; only + − × ÷ allowed.
     */
    public SubmitResult submitExpression(String expression) {
        if (attemptsLeft <= 0) {
            return SubmitResult.NO_ATTEMPTS_LEFT;
        }
        if (expression == null) {
            return SubmitResult.INVALID_EXPRESSION;
        }
        String normalized = expression.trim().replace('×', '*').replace('÷', '/').replace('−', '-');
        String compact = compactDropWhitespace(normalized);
        if (compact.isEmpty()) {
            return SubmitResult.INVALID_EXPRESSION;
        }

        List<Integer> usedNumbers = extractNumbersFromExpression(compact);
        if (usedNumbers.size() != NUMBERS_COUNT) {
            return SubmitResult.INVALID_NUMBERS;
        }
        boolean[] used = new boolean[NUMBERS_COUNT];
        for (int n : usedNumbers) {
            boolean found = false;
            for (int i = 0; i < NUMBERS_COUNT; i++) {
                if (!used[i] && currentNumbers[i] == n) {
                    used[i] = true;
                    found = true;
                    break;
                }
            }
            if (!found) {
                return SubmitResult.INVALID_NUMBERS;
            }
        }

        double result;
        try {
            result = new ExprParser(compact).parse();
        } catch (Exception e) {
            return SubmitResult.INVALID_EXPRESSION;
        }

        if (Double.isNaN(result) || Double.isInfinite(result) || result != Math.floor(result)) {
            return SubmitResult.INVALID_EXPRESSION;
        }
        int intResult = (int) Math.round(result);

        attemptsLeft--;
        if (intResult == currentTarget) {
            score += getScoreReward();
            puzzlesSolvedThisLevel++;
            if (puzzlesSolvedThisLevel >= PUZZLES_PER_LEVEL) {
                level++;
                puzzlesSolvedThisLevel = 0;
            }
            return SubmitResult.CORRECT;
        } else {
            if (attemptsLeft <= 0) {
                return SubmitResult.WRONG_ATTEMPTS_EXHAUSTED;
            }
            return SubmitResult.WRONG;
        }
    }

    private static String compactDropWhitespace(String s) {
        StringBuilder sb = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (!Character.isWhitespace(c)) {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    /** Extract integer operands (multi-digit numbers) from a compact expression. */
    private List<Integer> extractNumbersFromExpression(String compactExpr) {
        Matcher m = INTEGER_TOKEN.matcher(compactExpr);
        List<Integer> list = new ArrayList<>(NUMBERS_COUNT);
        while (m.find()) {
            try {
                list.add(Integer.parseInt(m.group()));
            } catch (NumberFormatException e) {
                return new ArrayList<>();
            }
        }
        return list;
    }

    public boolean isGameComplete() {
        return score >= TARGET_SCORE;
    }

    public enum SubmitResult {
        CORRECT,
        WRONG,
        WRONG_ATTEMPTS_EXHAUSTED,
        INVALID_EXPRESSION,
        INVALID_NUMBERS,
        NO_ATTEMPTS_LEFT
    }

    public static String getPerformanceRating(int score) {
        if (score < 40) return "Beginner";
        if (score < 70) return "Puzzle Player";
        if (score < 100) return "Puzzle Expert";
        return "Puzzle Champion 🏆";
    }
}
